# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57060575f42a6f70eaf1e419bdb87f7fb8646f5dda2a3050f25d04c71f2d64f719c6be74087f0ce99016aa327d2b975efb04bd6624f0ad3f0f62799d01d01edf

test:
  secret_key_base: 3f91e54161f70bbed4c7baeb3befd4e75ec2bf86255f4201be7cfdbf7abfd016cdf864bfe9dbb9a3848bb984957a6815c3192d8847305b69fda470776f59c84c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
